Documentation/UserManagement/GroupPermissions/Index.rst
Also an image for the checkboxes DB and file mount should be added here.
This is a missing information. It cost me about 3 hours to find this out.
=> BE user group should set the DB and file mount

Documentation/Index.rst, Documentation/Sitemap.rst
- Remove titlesonly from toctree on startpage to include subsections in main menu
- Add sitemap
Resolves: #32
=> Change toctree to include subsections

Documentation/UserManagement/BackendUsers/Index.rst
- Section about system maintainers is not relevant until TYPO3 9
=> Remove section about system maintainers (for TYPO3 8 branch)

Documentation/UserManagement/BackendUsers/Index.rst
- Section about system maintainers is not relevant until TYPO3 9
=> Remove section about system maintainers (for TYPO3 7)

Documentation/NextSteps/Developers/Index.rst
This is commit is intended to improve the overall readability of the Developers page.
Two minor changes include:
[+] Swap the order of Fluid and Exbase in the title and description of the opening section. I think its a fair argument to make
that new developers probably need to look at templating before making a start with Ext development.
[+] Make reference to the fact that a new edition of the Extbase book is being released this year.
=> Improve readability of Developers page

Documentation/Introduction/Index.rst
This commit is intended to improve the overall readability of the "How to read this tutorial section".
- Replace the title
- Remove section that describes this tutorial has being "hands on", bit subjective but I don't think its relevant to the reader
- Break out each of the content blocks into its own paragraph
=> Improve readability of "Introduction" paragraph

Documentation/Introduction/Index.rst
This commit is intended to improve the overall readability of the Version Select paragraph.
- The title has been extended, with the intent that its more descriptive
- Replace reference to "Links at the bottom of the page" to the Release drop down found at the top of the page
- Improve overall readability
=> Improve readability of "Version Select" paragraph

Documentation/UserManagement/GroupPermissions/Index.rst
Add note to inverting the behavior of allow/deny fields in Localconfiguration.php
That note was already there in older version (6.2) but not in following versions. 
I'm searched for that after an update to still use the old settings for that.
=> Add note to inverting allow/deny behavior fields

Documentation/Installation/DeployTYPO3.rst
Recommend using logging severity including WARNING or higher
for production.
Related: TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#351
Releases: master, 11.5
=> [SECURITY] Add information for logging

Documentation/Installation/DeployTYPO3.rst
Add recommendation for using HTTPS in production
Related: TYPO3-Documentation/TYPO3CMS-Reference-CoreApi:#351
Releases: 11.5, master
----
Not part of commit message
I accidentally changed 11.5 branch, but should not be problem to cherry-pick to master (instead of the other way around.
=> [SECURITY] Recommend using HTTPS in production

Documentation/Installation/Install.rst
People should know that they can't use a different value for 'docroot'. 
See also:
* https://github.com/TYPO3/get.typo3.org/issues/291
* https://github.com/TYPO3/TYPO3.CMS.BaseDistribution/issues/54
* https://github.com/drud/ddev/issues/3701
=> Update Install.rst - 'docroot' MUST be 'public'

Documentation/Installation/Install.rst
The current format shows the :sh: markup in the frontend
=> [BUGFIX] Add Link to --no-dev option

Documentation/IntroductionPackage/Index.rst
* Add installation-type-specific instructions for the CLI commands.
* Add full path to typo3 CLI (`vendor/bin/typo3`)
* Specify the exact DDEV CLI command (`ddev composer ...` and `ddev typo3 ...`)
Fixes #188
=> [DOCS] Provide correct commands for bash/powershell/ddev

Documentation/SystemRequirements/Index.rst
This will redirect to the latest release. Removing the
version number from the URL removes necessity to update
this page for every version.
=> [TASK] Remove version number for get.typo3.org

Documentation/SystemRequirements/Apache.rst.txt
The previous text was slightly misleading because not all modules
are a requirement for TYPO3. But the current modules are used
in the default .htaccess. Addressing this and adding a link
to the .htaccess file in the core makes it more clear and makes
it easier for people to followup and check the requirements
and how they are used - even if they have not yet installed
TYPO3.
=> Clarify section on Apache modules

Documentation/SystemRequirements/Apache.rst.txt
The module is NOT required for TYPO3. In fact, in the
default TYPO3 .htaccess directory listings are disabled:
`<IfModule mod_autoindex.c>`
Options -Indexes
`</IfModule>`
The module mod_autoindex is not required to disable the
directoriy listings. It provides the directory listings
in the first place (which can then be disabled).
So, if one wants to add the module, they can, but it is
not a requirement for TYPO3.
=> Remove required mod_autoindex

Documentation/Index.rst, Documentation/IntroductionPackage/Index.rst
This commit moves meta information to the bottom
of the landing page. The intent being to only show the
most relevant information above the fold.
=> Move meta information to the bottom of the landing page

Documentation/About.rst, Documentation/Installation/ReleaseIntegrity.rst, Documentation/SystemRequirements/Index.rst
Related: TYPO3-Documentation/TYPO3CMS-Guide-HowToDocument#295
Releases: main, 11.5
=> [TASK] Correct spelling of TYPO3 versions

Documentation/Installation/Install.rst
This commit reverts an earlier change that introduced
deployment information to the very beginning of the
installation guide. Detailed information on why / how we 
deploy TYPO3 without using Composer is already available in the
Deploying TYPO3 chapter.
[-] Revert changed
[+] Continue to remind users not use Composer in production
=> [TASK] Move deployment information out of installation chapter

Documentation/Installation/Install.rst
The existing install doesn't work if mutagen is enabled, I'm not sure why, but see the failure at https://gist.github.com/rfay/ecc92d820f1432384bcbe4ef24d06543
But the DDEV technique on https://ddev.readthedocs.io/en/latest/users/quickstart/#typo3-composer-build always works.
Note that this also changes the `typo3/cms-base-distribution:^11` to just `typo3/cms-base-distribution` so it doesn't have to be maintained on next release.
=> Use proven DDEV install technique that uses composer --no-install

Documentation/SystemRequirements/PHP.rst.txt
See: https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-96889-RequirePHPMbstringAndIntl.html
=> [TASK] Move PHP intl extension to required section

Documentation/SystemRequirements/PHP.rst.txt
Extension "hash" is a PHP core built in and can't be disabled. It's always there, no need to list it.
=> Remove 'hash' from required PHP extensions list

Documentation/SystemRequirements/PHP.rst.txt
See https://forge.typo3.org/issues/99842 - enabled by default, but does not hurt to list here.
=> [TASK] Add 'tokenizer' as required extension

Documentation/SystemRequirements/Index.rst
The Information was present in documentation for TYPO3 10, but is lost since 11. @see https://docs.typo3.org/m/typo3/guide-installation/10.4/en-us/In-depth/SystemRequirements/Index.html#system-requirements
=> [TASK] Restore GraphicsMagick or ImageMagick as an optional requirement

Documentation/Installation/Install.rst
In the steps for installing with ddev, a step is missing - to start the ddev server
=> fix: add missing command in steps

Documentation/Installation/Install.rst
In the steps for installing with ddev, a step is missing - to start the ddev server
=> fix: add missing command in steps (#286)

Documentation/SystemRequirements/PHP.rst.txt
In TYPO3v11 this is still optional and `symfony/polyfill-mbstring` used as fallback.
=> Remove "mbstring" from required PHP extensions (TYPO3v11)

Documentation/IntroductionPackage/Index.rst
Since TYPO3 11.5 it is essential to setup the extension afterwards by running the following command: composer exec typo3 extension:setup
Information from https://docs.typo3.org/p/typo3/cms-introduction/main/en-us/Installation.html
=> Update Index.rst: setup required for introduction package!

Documentation/SystemRequirements/PHP.rst.txt
php-mbstring ist optional because there is the fallback onto a polyfill. But for performance reasons it should be mentioned.
Example
Opening a EXT:news record with ~40 content elements attachached:
* without php-mbstring: ~40s response time
* with php-mbstring: ~1s response time
=> Re-add mbstring PHP extension

Documentation/Installation/Install.rst
The Composer Create Project chapter should not show the TYPO3 setup command.
=> remove duplicate typo3 setup

Documentation/Installation/Install.rst
When v12.0 came out ddev does not know about the moved file. Since that quite some ddev versions came out which can check the TYPO3 version and create the AdditionalConfiguration.php or the additional.php accordingly. So, the command to manually move the additional configuration can be removed.
=> [TASK] Remove moving AdditionalConfiguration.php from ddev tab

Documentation/Installation/LegacyInstallation.rst
As version 12.4 is used in the following code examples, it makes sense to remain consistent in this respect in the download code snippet.
=> Add latest LTS version in download code

Documentation/Installation/Install.rst
=> [TASK] Use version 13 for installation of TYPO3

Documentation/Installation/LegacyInstallation.rst
=> [TASK] Use version 13 for legacy installation of TYPO3

Documentation/Extensions/Index.rst, Documentation/Localization.ru_RU/Extensions/Index.rst, Documentation/Localization.ru_RU/Setup/Index.rst, Documentation/Localization.ru_RU/Troubleshooting/Index.rst, Documentation/Setup/Index.rst, Documentation/Troubleshooting/Index.rst
Sphinx allows this while it is not in the standard, the guides can currently not interpret it correctly
releases: main, 12.4, 11.5
=> [BUGFIX] Remove ".rst" endings from menues

Documentation/OtherBackendModules/BackendLocalization/Index.rst
Add a related link for people who are looking for managing frontend translations - just like here: https://docs.typo3.org/m/typo3/reference-coreapi/11.5/en-us/ApiOverview/Localization/ManagingTranslations.html
I don't know if the ref works here, is there a way to preview how the `:ref:'sitehandling-addinglanguages'` will be rendered?
=> Add link to sitehandling / adding languages. 

Documentation/Index.rst, Documentation/PermissionsManagement/Index.rst
This commit adds the first index page for `Permissions Management` under the `Getting Started` documentation section. Several upcoming patches will include subsections for the permissions management documentation.
=> [TASK] Add new section Permissions Managment inside Getting Started docs

Documentation/Localization.ru_RU/Installation/Install.rst
Additionally, translate "If you want to install another version of TYPO3 find documentation by using the version selector on the left side of this page." instead of linking directly to a version.
Releases: main
=> [TASK] Use TYPO3 v13 on Russian installation page

Documentation/Installation/Install.rst
With the release of TYPO3 v13.0.1 the stable version of Doctrine DBAL v4 is required. There is no need to set the minimum-stability anymore.
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/847
Releases: main
=> [TASK] Remove note about using RC for Doctrine DBAL v4

Documentation/Installation/ReleaseIntegrity.rst
Additionally:
- Add abbreviation for PGP
=> [TASK] Use text roles in "Release integrity" chapter

Documentation/Installation/Install.rst, Documentation/Installation/LegacyInstallation.rst
Adds a link from the end of the Legacy Install instructions to the "Access TYPO3 via a web browser" step in the standard instructions.
Also adds a warning admonition to the text about the Legacy Install instructions being out of date.
=> [TASK] Link to next instructions for Legacy Install section

Documentation/Installation/TutorialDdev.rst
* DDEV provides the `ddev typo3` command, so no ./vendor/bin is required.
* Note that ` vendor/bin` is in the $PATH anyway, so need not be listed. 
* PhpMyAdmin is no longer provided by default, so `ddev launch -p` no longer exists
=> docs: Minor updates to DDEV tutorial

Documentation/SystemRequirements/Database.rst.txt
This PR addresses a valid question from https://forge.typo3.org/issues/94100 to indicate which SQL_MODE settings
may be required. A small chat with @sbuerk revelead the current testing defaults which should be safe to mention here.
IMO further details can be clarified in a follow-up.
=> [TASK] Document SQL_MODE requirements / current state

Documentation/SystemRequirements/PHP.rst.txt
Hello,
I just had the issue, that news administrator module throws some JavaScript errors, because fluid VHs were not replaced in script-tag attributes nor within the script-tag itself.
Sure pcre.jit is enabled by default with PHP 8.0, but in Plesk systems this directive is deactivated.
=> Activate JIT compiler

Documentation/Installation/TutorialDdev.rst
The documented workflow doesn't work for ddev 1.23.3 anymore.
When the `--php-version` parameter is given, ddev doesn't ask for `type` and `docroot`.
Releases: main, 12.4, 11.5
=> [BUGFIX] Correct the DDEV configuration command for the current version

Documentation/FirstProject/Index.rst
Seems like we accidently removed it during updating getting started
=> Add missing anchor

Documentation/FirstProject/IntroductionPackage/Index.rst
Removes a set of tabs for "Composer-based installation" and "Legacy installation." These tabs repeat the content of the bash/powershell/ddev commands below. Also, the reference to legacy installation is unnecessary as bash/powershell/ddev all use Composer for installation.
=> Remove reference to composer/legacy in installation

Documentation/Installation/Install.rst
DDEV supports nginx with php-fpm by default (nginx-fpm) so we need to choose "other", instead "apache" beacause choosing "apache" create a .htaccess file not used by nginx. And it could be confusing for tutorial follower.
Releases : main, 13.4
=> Update Web Server Type

Documentation/Extensions/RecommendedExtensions.rst
The elasticsearch/elasticsearch package is not a TYPO3 extension but merely a library to interact with Elasticsearch. A proper TYPO3 integration needs custom code or packages like pagemachine/searchable.
Alternative to https://github.com/TYPO3-Documentation/TYPO3CMS-Tutorial-GettingStarted/pull/602
=> Recommend pagemachine/searchable extension

Documentation/Concepts/Backend/FileModule/Index.rst
It seems to me that this was overlooked, and that this (composer) link was intended to be used further down in the next paragraph (which has been done).
=> Remove faulty link text in "The Filelist module" (Getting Started Tutorial)

Documentation/Concepts/Assets/Index.rst, Documentation/Concepts/Backend/AdminTools/ContentSecurityPolicy.rst, Documentation/Concepts/Cache/Index.rst, Documentation/Concepts/TCA/Index.rst, Documentation/Concepts/TypoScript/Index.rst
- add missing space in sentence
- remove redundant words (I assume copy and paste errors)
- improve sentence structure
- use "top bar" wording instead of "toolbar" and add doc link (according to the [documentation](https://docs.typo3.org/m/typo3/tutorial-getting-started/main/en-us/Concepts/Backend/GeneralBackendStructure/TopBar/Index.html))
=> fix grammar and typos (TYPO3 concepts)

Documentation/FirstProject/CreateSitePackage.rst
Simple spelling mistake fixed in the Create Site package docs
Preported from #674, therefore already in 13.4
=> Update CreateSitePackage.rst (#674)

Documentation/Concepts/Backend/FileModule/Index.rst, Documentation/Installation/Updates/Index.rst, Documentation/Prerequisites/Index.rst
Replaces previous pull request made onto 13.4 branch. Per Stefan opening a new PR on main branch. Added a few additional typos from other document pages.
=> Fix Typos in Getting Started Tutorial

Documentation/Installation/Install.rst
There will be no prompt on DDEV version v1.24.3.
`--auto` defaults to true and can not be turned of with another flag. As no structure is within the folder, it defaults to
> Configuring a 'php' project named 't3example' with docroot '' at './t3example'.
which is the wrong layout and project type.
=> Updated DDEV steps

Documentation/FirstProject/SiteManagement/Index.rst
Updates the "Site Management" page with an attention admonition informing about the automated generation of page configurations when you create a page in the root of the page tree. Also adds another section header about editing the site configuration in order to keep creating and editing the site configuration as separate steps.
=> [BUGFIX] Mention that site config is auto generated for root pages

Documentation/Installation/Index.rst, Documentation/Installation/Install.rst, Documentation/Installation/Setup.rst, Documentation/Installation/UsingDdev.rst
- Assume DDEV and Composer as default
- Add quick start installation instructions
- Add setup for Development/DDEV application context
- Reorder cards and menu for better flow
- Link to full installation guide for alternatives
releases: main, 13.4
=> [TASK] Refactor installation and setup chapters

Documentation/ProjectTemplates/GitLabTemplate/Index.rst
=> Correct indentation

Documentation/Installation/DeployTYPO3.rst, Documentation/Installation/Updates/Index.rst
see https://docs.typo3.org/m/typo3/tutorial-getting-started/main/en-us/Installation/Updates/Index.html#extension-updates
=> Fix broken link in getting started

Documentation/Concepts/Backend/AdminTools/Index.rst
References: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1274
Releases: main
=> [FEATURE] Add CLI command install:password:set
