Documentation/FileModule/Index.rst
Documentation/fr_FR/ExtensionManager/Index.rst
Documentation/fr_FR/FileModule/Index.rst
Documentation/fr_FR/GeneralPrinciples/PageTree/Index.rst
Documentation/fr_FR/Index.rst
Documentation/fr_FR/ListModule/AdvancedClipboard/Index.rst
Documentation/fr_FR/ListModule/Clipboard/Index.rst
Documentation/fr_FR/ListModule/Index.rst
Documentation/fr_FR/ListModule/MassEditing/Index.rst
Documentation/fr_FR/ListModule/UsingEffectively/Index.rst
Documentation/fr_FR/UserManagement/BackendUsers/Index.rst
Documentation/fr_FR/UserManagement/GroupPermissions/Index.rst
Documentation/fr_FR/UserManagement/Groups/Index.rst
Documentation/fr_FR/UserManagement/Index.rst
Documentation/fr_FR/UserManagement/PagePermissions/Index.rst
Documentation/fr_FR/UserManagement/UserSetup/Index.rst

Bonjour,
J'ai traduit de nouvelles sections : 
- /ListModule/
- /FileModule/
- /ExtensionManager/
- /UserManagement/
Et fait une mise à jour de la syntaxe de la table des matière
/Index.rst

Mise à jour et nouvelle traduction

---

Documentation/OtherBackendModules/SystemModules/Index.rst
Documentation/fr_FR/NextSteps/Administrators/Index.rst
Documentation/fr_FR/NextSteps/Editors/Index.rst
Documentation/fr_FR/NextSteps/Index.rst
Documentation/fr_FR/NextSteps/References/Index.rst
Documentation/fr_FR/NextSteps/Security/Index.rst
Documentation/fr_FR/OtherBackendModules/BackendLocalization/Index.rst
Documentation/fr_FR/OtherBackendModules/Index.rst
Documentation/fr_FR/OtherBackendModules/InfoAndFunctions/Index.rst
Documentation/fr_FR/OtherBackendModules/SystemModules/Index.rst
Documentation/fr_FR/Troubleshooting/HumanReadableUrls/Index.rst
Documentation/fr_FR/Troubleshooting/ImageProcessing/Index.rst
Documentation/fr_FR/Troubleshooting/Index.rst

Bonjour,
voici la fin de la première version traduite.
Je corrigerai d'ici peu la traduction du terme "docheader" qui ne me convient pas trop.
Bonne journée

Finalisation de la traduction

---

Documentation/fr_FR/Introduction/Index.rst

Bonjour,
J'ai juste mis à jour les crédits en mettant mon nom pour la traduction FR.
Merci et bonne journée

[TASK] French translation update

---

Documentation/fr_FR/Introduction/Index.rst

Bonjour,
Correction d'accord.
Pour une intro c'est pas top...
Bonne journée,
Jonathan

[TASK] French translation correction

---

Documentation/UserManagement/GroupPermissions/Index.rst

see my comment at the end of 
https://github.com/TYPO3-Documentation/TYPO3CMS-Tutorial-GettingStarted/pull/15

misspelling

---

Documentation/ExtensionManager/Index.rst
Documentation/UserManagement/BackendUsers/Index.rst

https://github.com/TYPO3-Documentation/TYPO3CMS-Tutorial-GettingStarted/commit/9feff7bc97f6c29333806200fa9fb77e24785a5f

modify pull request #18

---

Documentation/Introduction/Index.rst
Documentation/NextSteps/Administrators/Index.rst
Documentation/NextSteps/Developers/Index.rst
Documentation/NextSteps/Editors/Index.rst
Documentation/NextSteps/Index.rst
Documentation/NextSteps/References/Index.rst
Documentation/NextSteps/Security/Index.rst
Documentation/Settings.cfg

- Add sitepackage tutorial to next step
- Add page with information for developers
- Add various videos from YouTube channel
- Add information about Slack to introduction

Add information to next steps (8.7)

---

Documentation/Introduction/Index.rst
Documentation/NextSteps/Administrators/Index.rst
Documentation/NextSteps/Developers/Index.rst
Documentation/NextSteps/Editors/Index.rst
Documentation/NextSteps/Index.rst
Documentation/NextSteps/References/Index.rst
Documentation/NextSteps/Security/Index.rst
Documentation/Settings.cfg

- Add sitepackage tutorial to next step
- Add page with information for developers
- Add various videos from YouTube channel
- Add information about Slack to introduction

Add information to next steps (7.6)

---

Documentation/ExtensionManager/Index.rst
Documentation/FileModule/Index.rst
Documentation/GeneralPrinciples/BackendAndFrontend/Index.rst
Documentation/GeneralPrinciples/ContextMenu/Index.rst
Documentation/GeneralPrinciples/GeneralBackendStructure/Index.rst
Documentation/GeneralPrinciples/PageTree/Index.rst
Documentation/GeneralPrinciples/Templates/Index.rst
Documentation/GeneralPrinciples/TopBar/Index.rst
Documentation/Installation/Index.rst
Documentation/Introduction/Index.rst
Documentation/ListModule/AdvancedClipboard/Index.rst
Documentation/ListModule/Clipboard/Index.rst
Documentation/ListModule/Index.rst
Documentation/ListModule/MassEditing/Index.rst
Documentation/ListModule/UsingEffectively/Index.rst
Documentation/NextSteps/Index.rst
Documentation/NextSteps/Security/Index.rst
Documentation/OtherBackendModules/BackendLocalization/Index.rst
Documentation/OtherBackendModules/Index.rst
Documentation/OtherBackendModules/InfoAndFunctions/Index.rst
Documentation/OtherBackendModules/SystemModules/Index.rst
Documentation/Troubleshooting/ImageProcessing/Index.rst
Documentation/Troubleshooting/Index.rst
Documentation/UserManagement/BackendUsers/Index.rst
Documentation/UserManagement/GroupPermissions/Index.rst
Documentation/UserManagement/Groups/Index.rst
Documentation/UserManagement/Index.rst
Documentation/UserManagement/PagePermissions/Index.rst
Documentation/UserManagement/UserSetup/Index.rst

- use title capitalization
- use standard header underline rules
https://docs.typo3.org/typo3cms/HowToDocument/WritingReST/HeadlinesAndSection.html

Fix title case

---

Documentation/ExtensionManager/Index.rst
Documentation/FileModule/Index.rst
Documentation/GeneralPrinciples/BackendAndFrontend/Index.rst
Documentation/GeneralPrinciples/ContextMenu/Index.rst
Documentation/GeneralPrinciples/GeneralBackendStructure/Index.rst
Documentation/GeneralPrinciples/PageTree/Index.rst
Documentation/GeneralPrinciples/Templates/Index.rst
Documentation/GeneralPrinciples/TopBar/Index.rst
Documentation/Installation/Index.rst
Documentation/Introduction/Index.rst
Documentation/ListModule/AdvancedClipboard/Index.rst
Documentation/ListModule/Clipboard/Index.rst
Documentation/ListModule/Index.rst
Documentation/ListModule/MassEditing/Index.rst
Documentation/ListModule/UsingEffectively/Index.rst
Documentation/NextSteps/Index.rst
Documentation/NextSteps/Security/Index.rst
Documentation/OtherBackendModules/BackendLocalization/Index.rst
Documentation/OtherBackendModules/Index.rst
Documentation/OtherBackendModules/InfoAndFunctions/Index.rst
Documentation/OtherBackendModules/SystemModules/Index.rst
Documentation/Troubleshooting/ImageProcessing/Index.rst
Documentation/Troubleshooting/Index.rst
Documentation/UserManagement/BackendUsers/Index.rst
Documentation/UserManagement/GroupPermissions/Index.rst
Documentation/UserManagement/Groups/Index.rst
Documentation/UserManagement/Index.rst
Documentation/UserManagement/PagePermissions/Index.rst
Documentation/UserManagement/UserSetup/Index.rst

- use title capitalization
- use standard header underline rules
https://docs.typo3.org/typo3cms/HowToDocument/WritingReST/HeadlinesAndSection.html

Fix title case (7.6)

---

Documentation/GeneralPrinciples/BackendAndFrontend/Index.rst
Documentation/GeneralPrinciples/ContextMenu/Index.rst
Documentation/GeneralPrinciples/GeneralBackendStructure/Index.rst
Documentation/GeneralPrinciples/Index.rst
Documentation/GeneralPrinciples/PageContent/Index.rst
Documentation/GeneralPrinciples/PageTree/Index.rst
Documentation/GeneralPrinciples/Templates/Index.rst
Documentation/GeneralPrinciples/TopBar/Index.rst
Documentation/Installation/Index.rst

This is based on PR #62 by @tomwarwick. I resolved merge conflicts.

Improve readability of Introduction and General Principles pages II

---

Documentation/Installation/Index.rst

Remove outdated link to TYPO3Winstaller (8.7)

---

Documentation/Installation/Index.rst

Remove outdated link to TYPO3Winstaller (7.6)

---

Documentation/ListModule/Index.rst

This commit is intend to improve the overall readability of the Introduction page for the ListModule section.
- Describe what the List Module does
- Give examples of different types of page content
- Explain its use for Extension that don't have a dedicated Module in the BE

Improve readability of List Module / Introduction page

---

Documentation/NextSteps/Administrators/Index.rst
Documentation/NextSteps/Index.rst
Documentation/NextSteps/Integrators/Index.rst

- Page Administrators.rst addressed integrators, content now moved so that
file name and content is consistend

Clean up confusing name mixup in Next Steps section

---

Documentation/NextSteps/Editors/Index.rst

Minor changes, removed additional title at the top fo the page.

Importe readability of Editors page

---

Documentation/OtherBackendModules/InfoAndFunctions/Index.rst

Improve readability of Info and Functions page

---

Documentation/UserManagement/BackendUsers/Index.rst

Improve readability of Backend Users page

---

Documentation/Settings.cfg

Link to documentation team page on typo3.org as contact

---

Documentation/GeneralPrinciples/ContextMenu/Index.rst
Documentation/ListModule/MassEditing/Index.rst

fix typos (9.5)

---

Documentation/OtherBackendModules/BackendLocalization/Index.rst

refs https://github.com/TYPO3-Documentation/t3docs-screenshots/issues/147

[BUGFIX] Fix rendering

---

Documentation/NextSteps/Developers/Index.rst

See https://github.com/TYPO3-Documentation/T3DocTeam/issues/161 for details.

[TASK] Update TYPO3 repository URL

---

Documentation/Images/AutomaticScreenshots/QuickInstall/LoginScreen.rst.txt

[TASK] Fix wrong reference

---

Documentation/Installation/Install.rst

Fix install URL

---

Documentation/Extensions/Index.rst

Fix link to local extensions

---

Documentation/Setup/SiteRecords.rst

See TYPO3-Documentation/T3DocTeam#164 for details.

[TASK] Disable all dummy urls with `:samp:`

---

Documentation/Installation/LegacyInstallation.rst
Documentation/Installation/ReleaseIntegrity.rst

Update TYPO3 version to match LTS

---

Documentation/SystemRequirements/Index.rst

Also clarify that TYPO3 11 requires Composer 2.1.0

Recommend latest Composer version

---

Documentation/Concepts/Index.rst
Documentation/Installation/DeployTYPO3.rst
Documentation/Setup/SiteRecords.rst

See TYPO3-Documentation/T3DocTeam#165 for details.

[TASK] Unify top-level domain of dummy urls

---

.editorconfig
Documentation/GeneralPrinciples/BackendAndFrontend/Index.rst
Documentation/Index.rst
Documentation/Localization.fr_FR/Index.rst
Documentation/Localization.fr_FR/Installation/Index.rst
Documentation/Localization.fr_FR/Introduction/Index.rst
Documentation/Localization.fr_FR/NextSteps/Index.rst
Documentation/Localization.fr_FR/NextSteps/Security/Index.rst
Documentation/Localization.fr_FR/Troubleshooting/HumanReadableUrls/Index.rst
Documentation/Localization.fr_FR/_make/README.rst
Documentation/Localization.fr_FR/_make/conf.py
Documentation/NextSteps/Index.rst

See TYPO3-Documentation/T3DocTeam#166 for details.

[TASK] Unify placeholder syntax

---

Documentation/Installation/Install.rst

How can dependencies be removed?

replace "dependencies are completely removed"

---

Documentation/UserManagement/GroupPermissions/Index.rst

Document category mounts

---

Documentation/Extensions/LegacyManagement.rst
Documentation/Extensions/Management.rst
Documentation/Installation/DeployTYPO3.rst
Documentation/Installation/Install.rst
Documentation/Installation/LegacyInstallation.rst
Documentation/Installation/ReleaseIntegrity.rst
Documentation/IntroductionPackage/Index.rst
Documentation/Settings.cfg
Documentation/SystemRequirements/NGINX.rst.txt
Documentation/Troubleshooting/PHP.rst
Documentation/Troubleshooting/SystemModules.rst
Documentation/Troubleshooting/TYPO3.rst
Documentation/Troubleshooting/WebServer.rst

to make it more clear where code should go
Releases: main, 11.5

[TASK] Add captions to code-blocks

---

Documentation/Installation/Install.rst

* Install.rst: Web server entry path hint
* Update Documentation/Installation/Install.rst
Cherry pick of https://github.com/TYPO3-Documentation/TYPO3CMS-Tutorial-GettingStarted/pull/202 
Co-authored-by: Mathias Brodala <mbrodala@pagemachine.de>
* Update Documentation/Installation/Install.rst
Co-authored-by: Mathias Brodala <mbrodala@pagemachine.de>
Co-authored-by: Lina Wolf <48202465+linawolf@users.noreply.github.com>
Co-authored-by: Mathias Brodala <mbrodala@pagemachine.de>

Install.rst: Web server entry path hint (#202)

---

Documentation/Index.rst

So that new visitors do not get distracted
Releases: main, 11.5

[TASK] Switch the version information to the bottom

---

Documentation/SystemRequirements/PHP.rst.txt

Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/92

[TASK] Remove SQL Server

---

Documentation/Index.rst

Changes to the documentation structure should be handled by
1) discussing them in the documentation team channel
2) composing a new standard in the related documentation pages
3) applying the new standard to all official manuals
4) republishing the new standard

Revert "[TASK] Switch the version information to the bottom (#212)"

---

Documentation/SystemRequirements/PHP.rst.txt

This makes that part more readable (for people
familiar with the settings) and eases copy-paste.

Change php.ini settings to codeblock

---

Documentation/Installation/Index.rst
Documentation/Installation/TuneTYPO3.rst

[TASK] Add Tuning TYPO3 chapter

---

.editorconfig

Switch default spaces to 4

---

Documentation/Installation/Index.rst
Documentation/Installation/Install.rst
Documentation/Installation/TutorialDdev.rst

Tutorial: Install TYPO3 on DDEV

---

Documentation/Settings.cfg

[TASK] Remove references to the extbase book

---

Documentation/Installation/Install.rst

The previous sentence can be easaly misunderstood

Installation of composer on dev systems

---

Documentation/Troubleshooting/TYPO3.rst

[TASK] Correct spelling of example.com domains

---

Documentation/Installation/Install.rst
Documentation/Installation/TutorialDdev.rst
Documentation/Settings.cfg

Version 12.0 was released this morning. Here is the information on how to install it.
Releases: main

[FEATURE] Install TYPO3 v12.0

---

Documentation/Installation/DeployTYPO3.rst
Documentation/Installation/TutorialDdev.rst
Documentation/Troubleshooting/TYPO3.rst
Documentation/UserManagement/BackendPrivileges/Index.rst

References https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/204
releases: main

Move LocalConfiguration to system/settings.php

---

Documentation/Installation/DeployTYPO3.rst

Refs #204 
Is it possible to add the `hacktoberfest-accepted` label?

Do not use specific repository

---

Documentation/Setup/SiteRecords.rst

Refs #223
Is it possible to add the hacktoberfest-accepted label?

Remove wrong info about languages

---

Documentation/Setup/BackendLanguages.rst

[TASK] Reformat chapter "Backend languages"

---

Documentation/Setup/BackendLanguages.rst

Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/238

[FEATURE] #98957 - Respect write-protected settings.php in Install Tool

---

Documentation/Installation/Install.rst
Documentation/Installation/TutorialDdev.rst

references https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/283

[FEATURE] Add a command to set up TYPO3

---

Documentation/Installation/Install.rst

Additionally, generalize TYPO3 v12 version number
Releases: main

[TASK] Link "CLI command" to appropriate chapter

---

Documentation/Installation/Install.rst

Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/298
Releases: main

[TASK] Mention password policy in installation process

---

Documentation/Concepts/Index.rst

Small changes to improve readability

Small changes

---

Documentation/Concepts/Index.rst

Forward-port of https://github.com/TYPO3-Documentation/TYPO3CMS-Tutorial-GettingStarted/pull/267

Improve readability of concepts chapter (#267)

---

Documentation/Installation/Install.rst

[Forwardport] Minor language fixes

---

Documentation/Installation/Install.rst

Referring to the Composer documentation https://getcomposer.org/doc/03-cli.md#create-project, the syntax for creating a project seems to differ here!?

Adjust command for creating a Composer project (#283)

---

Documentation/SystemRequirements/Index.rst

[TASK] Overhaul system requirements

---

Documentation/Concepts/Index.rst

Overhaul TYPO3 concepts

---

Documentation/IntroductionPackage/Index.rst

[TASK] Follow Up setup required for introduction package

---

Documentation/IntroductionPackage/Index.rst

Preport of #281 to main and 12.4
Thanks again at @JHeuper

[Preport] Setup required for introduction package

---

Documentation/Installation/Install.rst

It will not work if the create command is executed outside of the allowed webserver directories.

Give info about root directory

---

Documentation/Installation/Install.rst

- Add a TOC
- Streamline wordings
- Add some references where appropriate

[TASK] Revise installation chapter

---

composer.json

[TASK] Use recent LTS version

---

.gitignore
composer.json

Additionally, ignore composer.lock file
Releases: main

[TASK] Require dev-main as TYPO3 constraint

---

Documentation/Installation/ReleaseIntegrity.rst

- Use TYPO3 v12.4 as example
- Adjust indentations

[TASK] Streamline "Release integrity" chapter

---

Documentation/Installation/ReleaseIntegrity.rst

- Use TYPO3 v12.4 as example
- Adjust indentations

[TASK] Streamline "Release integrity" chapter (#349)

---

Documentation/Installation/TutorialDdev.rst

Follow-up to #364; already backported to 11.5 and 12.4

[TASK] Remove "create-docroot" related section remains

---

Documentation/Concepts/Index.rst
Documentation/Localization.ru_RU/Concepts/Index.rst

Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/813
Releases: main

[FEATURE] #87889 - Make backend URL configurable

---

Documentation/Index.rst

- use card-directives instead of containers
- Add buttons with links and action labels
- use sentence case
- correct indentation
After:
Before:

[TASK] Overhaul start page

---

Documentation/Index.rst

Small language improvements
Releases:main, 12.4

Overhaul TYPO3 Tutorial Getting Started

---

Documentation/Installation/Install.rst

see 
https://typo3.slack.com/archives/C028JEPJL/p1711912673529259

The var folder is not generated by the command.

---

Documentation/Installation/DeployTYPO3.rst

Add Bash class to composer command

---

Documentation/Extensions/LegacyManagement.rst
Documentation/Extensions/Management.rst
Documentation/IntroductionPackage/Index.rst

[TASK] Replace external links with composer and t3ext roles

---

Documentation/Installation/Install.rst

[TASK] Add hint about composer command needing an empty directors

---

Documentation/Installation/Deployer/Index.rst

Fix broken link

---

Documentation/Troubleshooting/TYPO3.rst

Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/136
Releases: main

[TASK] use TypoScript instead of template

---

Documentation/Installation/TutorialDdev.rst

The average integrator might not now that apache and mysqli have to be used here or how to set up the database.

List answers for typo setup questions as to be used with DDEV

---

Documentation/Installation/TutorialDdev.rst

Suggest to start with PHP 8.3

---

Documentation/Installation/Install.rst

Preport from https://github.com/TYPO3-Documentation/TYPO3CMS-Tutorial-GettingStarted/pull/273
Co-authored-by: Sarah McCarthy <sarahmccarthy123@yahoo.com>
(cherry picked from commit a2df88cf0ad08d03074c661ca9dc4b65c62c6620)

Minor language fixes

---

Documentation/Includes.rst.txt

[TASK] Add end of life hint

---

Documentation/Troubleshooting/BackendLogin.rst
Documentation/Troubleshooting/Index.rst

[TASK] Write a chapter on backend login trouble shooting

---

.github/workflows/tests.yml
.gitignore
Build/.gitignore
Build/.php-cs-fixer.dist.php
Build/Scripts/runTests.sh
Build/Scripts/validateRstFiles.php
Makefile
composer.json

Manual backport to 12.4 needed
Releases: main, 13.4, 12.4

[TASK] Introduce runTest.sh for unified testing.

---

Documentation/Troubleshooting/Index.rst

Resolves: https://github.com/TYPO3-Documentation/TYPO3CMS-Tutorial-GettingStarted/issues/537
Releases: main, 13.4

[BUGFIX] Fix Card Link in Trouble shooting

---

Documentation/Includes.rst.txt

[TASK] Add hint for test phase

---

Documentation/Concepts/Backend/ListModule/Index.rst
Documentation/Concepts/Backend/PageModule/Index.rst
Documentation/Concepts/Backend/SiteManagement/PageTSconfig.rst
Documentation/FirstProject/Settings.rst

[TASK] Adjust links to TSconfig reference

---

Documentation/Concepts/Fluid/Index.rst

This is an attempt to streamline and to reduce the introduction to Fluid. I tried to reduce the dependencies, such as language handling, which should probably be part of a separate chapter. I also tried to make it more practical by providing some concrete examples.
I'm not sure if the actual implementation of partials and layouts should already be explained here or if it's sufficient to explain the concept and pick up the implementation at a later stage in the tutorial.

[DOC] Rewrite Fluid introduction chapter

---

Documentation/Includes.rst.txt

[TASK] Remove call for testing

---

Documentation/Installation/ApplicationContext.rst
Documentation/Installation/_ApplicationContext/_docker-compose.context.yaml

Please check here for more details: 
https://docs.docker.com/reference/compose-file/version-and-name/#version-top-level-element-obsolete

[DOCS] Docker Compose version Attribute Deprecation

---

Documentation/Concepts/Backend/SystemModules/Index.rst

Add cron job hints to scheduler

---

Documentation/Installation/SystemRequirements/Index.rst

[BUGFIX] Link to the advanced system requirements at TYPO3 Explained

---

Documentation/Concepts/Backend/AdminTools/Index.rst

[BUGFIX] Fix link

---

Documentation/NextSteps/Index.rst

[BUGFIX] Fix links to yaml chapter

---

Documentation/Concepts/Backend/GeneralBackendStructure/TopBar/Index.rst

To add a bookmark you need to use Share Icon menu dropdown in the DocHeader. Clicking on the star doesn't bookmark a page.

Correct Bookmark Icon Functionality Description

---

Documentation/Installation/Install.rst

Remove outdated version hint

---

Documentation/Concepts/TCA/Index.rst
Documentation/Installation/Install.rst

[BUGFIX] Fix links for TCA concept

---

Documentation/Concepts/Backend/SystemModules/Index.rst

References: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1239
Releases: main

[!!!][TASK] Remove "Database Relations" backend module

---

Documentation/Installation/Install.rst

Fix link syntax

---

Documentation/Installation/Hosting.rst
Documentation/Installation/Index.rst

[TASK] Hosting provider considerations for TYPO3 projects
